name: si-workshop
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - snakemake
  - pip
  - pip:
      - msprime
      - matplotlib
      - tskit
      - jupyter
      - ipykernel
      - numpy==2.3.5
